name: taxi_analytics
version: '1.0.0'
config-version: 2
profile: taxi_analytics
model-paths: [models]
macro-paths: [macros]
test-paths: [tests]
models:
  taxi_analytics:
    staging:
      +materialized: view
    marts:
      +materialized: table
